version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
            - ./node_modules
      - run:
          name: angular-build
          command: npm ng -- build --prod --aot --no-progress
      - run:
          name: angular-test
          command: npm ng test -- --single-run --no-progress
      - store_artifacts:
          path: test-results.xml