version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
jobs:
  build:
    working_directory: ~/league-app
    docker:
      - image: circleci/node:14-browsers
        environment:
          CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
            - ./node_modules
      - run:
          name: unit-test
          # run lib test and app test in the CI
          command: npm run test-lib-ci && npm run test-ci
      - store_artifacts:
          path: test-results.xml
      - run:
          name: prod-build
          command: npm run build
